"""empty message

Revision ID: 02834e7e25df
Revises: b1bfae2477c1
Create Date: 2024-10-25 09:36:07.765741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02834e7e25df'
down_revision = 'b1bfae2477c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###
